"""create_all_tables

Revision ID: 119a27a439fe
Revises: 
Create Date: 2026-04-27 00:56:21.983827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '119a27a439fe'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('cognito_sub', sa.String(length=255), nullable=False),
    sa.Column('slack_webhook_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('cognito_sub'),
    sa.UniqueConstraint('email')
    )
    op.create_table('aws_accounts',
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role_arn', sa.String(length=500), nullable=False),
    sa.Column('aws_account_id', sa.String(length=20), nullable=False),
    sa.Column('account_alias', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('connected_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_table('projects',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('prefix', sa.String(length=20), nullable=False),
    sa.Column('environment', sa.String(length=20), nullable=False),
    sa.Column('region', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('dr_status', sa.String(length=20), nullable=False),
    sa.Column('last_deployed_at', sa.DateTime(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['aws_accounts.account_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('aws_resources',
    sa.Column('resource_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_name', sa.String(length=255), nullable=False),
    sa.Column('resource_id_aws', sa.String(length=500), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('resource_id')
    )
    op.create_table('deployments',
    sa.Column('deployment_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('prefix', sa.String(length=20), nullable=False),
    sa.Column('environment', sa.String(length=20), nullable=False),
    sa.Column('terraform_code', sa.Text(), nullable=False),
    sa.Column('config_snapshot', sa.JSON(), nullable=False),
    sa.Column('validation_result', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('completed_resources', sa.Integer(), nullable=True),
    sa.Column('total_resources', sa.Integer(), nullable=True),
    sa.Column('ecs_task_id', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('deployment_id')
    )
    op.create_table('sync_history',
    sa.Column('sync_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('trigger_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('snapshot_status', sa.String(length=20), nullable=False),
    sa.Column('aws_resources_detected', sa.Integer(), nullable=True),
    sa.Column('gcp_resources_mapped', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('sync_id')
    )
    op.create_table('deployment_resources',
    sa.Column('resource_id', sa.String(length=36), nullable=False),
    sa.Column('deployment_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_name', sa.String(length=255), nullable=False),
    sa.Column('resource_arn', sa.String(length=500), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['deployment_id'], ['deployments.deployment_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('resource_id')
    )
    op.create_table('dr_packages',
    sa.Column('package_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('sync_id', sa.String(length=36), nullable=False),
    sa.Column('s3_path', sa.String(length=500), nullable=False),
    sa.Column('terraform_code_path', sa.String(length=500), nullable=False),
    sa.Column('image_ref_path', sa.String(length=500), nullable=True),
    sa.Column('gcr_image_uri', sa.String(length=500), nullable=True),
    sa.Column('snapshot_ref_path', sa.String(length=500), nullable=True),
    sa.Column('snapshot_export_s3_path', sa.String(length=500), nullable=True),
    sa.Column('snapshot_status', sa.String(length=20), nullable=False),
    sa.Column('rto_minutes', sa.Integer(), nullable=False),
    sa.Column('rpo_minutes', sa.Integer(), nullable=False),
    sa.Column('confidence_auto', sa.Integer(), nullable=False),
    sa.Column('confidence_review', sa.Integer(), nullable=False),
    sa.Column('confidence_manual', sa.Integer(), nullable=False),
    sa.Column('checklist', sa.JSON(), nullable=False),
    sa.Column('is_latest', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.ForeignKeyConstraint(['sync_id'], ['sync_history.sync_id'], ),
    sa.PrimaryKeyConstraint('package_id')
    )
    op.create_table('gcp_mappings',
    sa.Column('mapping_id', sa.String(length=36), nullable=False),
    sa.Column('resource_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('sync_id', sa.String(length=36), nullable=False),
    sa.Column('gcp_resource_type', sa.String(length=100), nullable=False),
    sa.Column('gcp_resource_name', sa.String(length=255), nullable=False),
    sa.Column('terraform_code', sa.Text(), nullable=False),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.Column('review_reason', sa.Text(), nullable=True),
    sa.Column('user_confirmed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['aws_resources.resource_id'], ),
    sa.ForeignKeyConstraint(['sync_id'], ['sync_history.sync_id'], ),
    sa.PrimaryKeyConstraint('mapping_id')
    )
    op.create_table('failover_history',
    sa.Column('failover_id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('package_id', sa.String(length=36), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('gcp_region', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('gcp_resources_created', sa.Integer(), nullable=True),
    sa.Column('actual_rto_seconds', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['package_id'], ['dr_packages.package_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.PrimaryKeyConstraint('failover_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('failover_history')
    op.drop_table('gcp_mappings')
    op.drop_table('dr_packages')
    op.drop_table('deployment_resources')
    op.drop_table('sync_history')
    op.drop_table('deployments')
    op.drop_table('aws_resources')
    op.drop_table('projects')
    op.drop_table('aws_accounts')
    op.drop_table('users')
    # ### end Alembic commands ###
